Try to create an example VMOD in go but failed with link error
+./libvmod_example.go:64: undefined reference to `WS_Reserve'
+./libvmod_example.go:50: undefined reference to `WS_Release'
These two functions are defined in varnishd, not in libvarnishapi.so.